#!bin/bash
#Level2

Church() {

        echo -e "\n====Level 2====\n"
        echo -e "\nYou and your friends ride across town and arrive at the church. The church is slowly withering away, the doorchained with a lock, the outside is graffitied, painting chipping away, a few busted windows, and overgrown weeds around.\n"

        echo -e "\nYour group looks around the church, and decides to break the lock to open the door.\n"

sleep 0.5

        Church1=("(1) Use a hammer"
                "(2) Use a bolt cutter?"
                "(3) Karate chop the lock, since you're a black belt?"
                "(4) Ram the door to try and open it with a bike?")

sleep 0.5

        IFS=""
        for choice in ${church1_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done

        sleep 0.5
        echo "Waiting for your move..."

read answer

sleep 0.5

case $answer in
        1)
                echo -e "You use the hammer, after hitting it a few times the lock breaks open. You take the chain off and pull open the doors."
                hammer
                ;;

        2)
                echo -e "After 15 minutes of trying to cut the lock open, it doesn't cut the lock. Would you like to try something else?"
                bolt_cutter
                ;;

        3)
                echo -e "Great! you broke your hand and will need to be transported to the hospital."
                karate_chop
                ;;

        4)
                echo -e "You try to ram the door open with your bike and it doesn't work. In the process your front tire is bent, looks like you will have to hitch a ride back with one of your friends."
                bike
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

hammer() {

        ham_choices=("(1) Check the map for clues?"
                "(2) Search around the church?"
                "(3) See if the doors on the stage are open?")

        echo -e "\nYou enter the church, a few pews left, a wooden cross on the front center wall, wooden pillars with symbols on it, and a couple of doors leading behind the stage.\n"

sleep 0.5

#        echo -e "\nWhere would you like to search first?\n"

sleep 0.5

        IFS=""
        for choice in ${ham_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5
        echo "Waiting for your move..."

       read answer

sleep 0.5

case $answer in
        1)
                echo -e "Checking the map for clues."
                map
                ;;

        2)
                echo -e "Your group begins to look around the church for clues."
                lookaround
                ;;

        3)
                echo -e "You walk towards the doors and jiggle the door knobs, they seem to be unlocked."
                doors
                ;;

        5)
                echo -e "Checking another room for clues"
                another_room

        esac
}

sleep 0.5

bolt_cutter() {

        bc_choices=("(1) Try the hammer?"
                "(2) Karate chop the lock, since you're a black belt?"
                "(3) Try ramming the door open with your bike?"
                "(4) Comeback another day with something better?")


        echo -e "\nWould you like to try something else?\n"
        echo -e "\nComeback another day with another tool to help you open the lock?\n"   

sleep 0.5

        for choice in ${bc_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5
        echo "Waiting for your move..."

        read answer

sleep 0.5

case $answer in
        1)
                echo -e "You use the hammer, after hitting it a few times the lock breaks open. You take the chain off and pul the doors open."

                hammer
                ;;

        2)
                echo -e "Great! you broke your hand and will need to be transported to the hospital."
                karate_chop
                ;;

        3)
                echo -e "You try to ram the door open with your bike and it doesn't work. In the process your front tire is be
nt, looks like you will have to hitch a ride back with one of your friends."
                bike
                ;;

        4)
                echo -e "You comeback another day and the church is demolished, now you will never be able to find the treasure."
                comeback
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

karate_chop() {

        echo -e "\nOne of your friends says At least now you could get it amputated and attach a hook. Then you'll just need an eye patch and a hat. You try not to laugh to much because it hurts"

sleep 0.5

        echo -e "\nLooking through the bookshelf you don't find anything but some notes in one of the pirates books, which happend to be on the section of Captain Kraven.\n"

sleep 0.5

        kc_choices=("(1) Search the fireplace?"
                "(2) Search the bust?"
                "(3) Search the locked antique chest?"
                "(4) Go back & check another room?")

#       echo "(1)Search the fire place?"
#       echo "(2)Examine the headstone?"
#       echo "(3)Check the locked antique chest?"
#       echo "(4)Check another room?"

        for choice in ${kc_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done

        sleep 0.5
        echo "Waiting for your move..."

        read answer

sleep 0.5

case $answer in
        1)
                echo -e 'Searching the fireplace'
                fireplace
                ;;

        2)
                echo -e 'Searching the bust'
                bust
                ;;

        3)
                echo -e 'Searching the locked antique chest'
                antique_chest
                ;;

        4)
                echo -e "Checking another room for clues"
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;
        
        esac

}

sleep 0.5

bike() {

        bike1_choices=("(1) Search the fireplace?"
                "(2) Search the bookshelf?"
                "(3) Search the locked Antique Chest?"
                "(4) Go back & check another room?")


        echo -e "\nSeems to just be a plain stone headstone.\n"

#       echo "(1)Search the fire place?"
#       echo "(2)Search the bookshelf?"
#       echo "(3)Check the locked antique chest?"
#       echo "(4)Check another room?"

        for choice in ${bike1_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e 'Searching the fireplace'
                fireplace
                ;;
        1)
                echo -e 'Searching the bookshelf.'
                bookshelf
                ;;
        2)
                echo -e 'Searching the locked antique chest'
                antique_chest
                ;;

        2)
                echo -e "Checking another room for clues"
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

antique_chest() {
        echo -e "\nYou see a table lamp and use it to break the lock. You open the chest and it seems to be full of old blankets and fabrics. You remove everything out of the chest and seems to be nothing out of the ordinary.\n"

        ac_choices=("(1) Search the fireplace?"
                "(2) Search the bookshelf?"
                "(3) Seach the bust?"
                "(4) Go back & check another room?")

#       echo "(1)Search the fire place?"
#        echo "(2)Search the bookshelf?"
#        echo "(3)Examine the headstone?"
#        echo "(4)Go back to the entryway"

        for choice in ${ac_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e 'Searching the fireplace'
                fireplace
                ;;

        2)
                echo -e 'Searching the bookshelf'
                bookshelf
                ;;

        3)
                echo -e 'Searching the bust'
                bust
                ;;

        4)
                echo -e "Checking another room for clues"
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

another_room() {

        echo -e "\nWhere would you like to search next?\n"

        ar_choices=("(1) Search the livingroom?"
                "(2) Search the kitchen?"
                "(3) Search the basement?"
               "(4) Search the bedroom?")

#        echo "(1)Search the livingroom?"
#        echo "(2)Search the kitchen?"
#        echo "(3)Check the basement?"
#        echo "(4)Check the bedroom?"

        for choice in ${ar_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
               echo -e 'Searching the livingroom'
                living_room
                ;;

        2)
                echo -e 'Searching the kitchen'
                kitchen
                ;;

        3)
                echo -e 'Searching the basement'
                basement
               ;;

        4)
                echo -e "Searching the bedroom"
                bedroom
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

room() {
       echo -e "\nYou enter the kitchen and the only things that seem to be left are an old gas stove and a dining table.\n"

        kitchen_choices=("(1) Search the kitchen cabinets?"
                "(2) Go back & check another room?")


        echo "(1)Check the kitchen cabinets?"
        echo "(2)Check another room?"

        for choice in ${kitchen_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5
       echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e 'Searching the kitchen cabinets.'
                kitchen_cabinets
                ;;

        2)
                echo -e "Checking another room for clues"
               another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

kitchen_cabinets() {

        echo -e "\nYou check the kitchen cabinets and they're empty. Nothing left but a few old mouse traps and some dishes.\n"

        kitcab_choices=("(1) Search the kitchen cabinets?"
                "(2) Go back & check another room?")
#        echo "(1)Check another room?"

        for choice in ${kitcab_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

       read answer

        sleep 0.5

case $answer in
        1)
                echo -e "Checking another room for clues"
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

basement() {

        echo -e "\n"                                                                

        basement_choices=("(1) Search the desk?"
                "(2) Go back & check another room?")


#        echo "(1)Search the desk?"
#        echo "(2)Check another room?"

        for choice in ${basement_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e "You search the desk but its empty, nothing but empty envelopes and writing paper."
                desk
                ;;

        2)
                echo -e "Check another room for clues"
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

       esac

}

sleep 0.5

desk() {
        echo -e "\nWhere would you like to search next?\n"

        desk_choices=("(1) Go back & check another room?")


#        echo "(1)Check another room?"

        for choice in ${desk_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e "Checking another room for clues"
               another_room
                ;;

        2)      echo -n "invalid"
                ;;

        esac

}

sleep 0.5

bedroom() {
        echo -e "\nYou enter the bedroom, just a couple of things left a bed and a dresser.\n"

        bedroom_choices=("(1) Search the dresser?"
                "(2) Search under the bed?"
                "(3) Go back & check another room?")

#       echo "(1)Check the dresser?"
#       echo "(2)Check under the bed?"
#       echo "(3)Check another room for clues?"

        for choice in ${bedroom_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e "Searching the dresser."
                dresser
                ;;

        2)
                echo -e "Searching under the bed."
                bed
                ;;

        3)
                echo -e "Checking another room for clues."
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

dresser() {
        echo -e "\nAs you walk over to the dresser to search it, you noticed a discolored and loose floor board. Upon closer inspection you notice that it's loose.\n"

        dresser_choices=("(1) Lift the floorboard?"
                "(2) Might be nothing, search the dresser instead?"
                "(3) search under the bed?"
                "(3) Go back & check another room?")

#        echo "(1)Lift the floorboard?"
#       echo "(2)Might be nothing, check the dresser instead?"
#        echo "(3)Check under the bed?"
#        echo "(4)Check another room for clues?"

        for choice in ${dresser_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)      echo -e "You lift the floor board and find a small wooden box."
                floorboard
                ;;

        2)      echo -e "Checking the dresser."
                check_dresser
                ;;

        3)
                echo -e "Checking under the bed."
                bed
                ;;
       4)
                echo -e "Checking another room for clues."
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

check_dresser() {
        echo -e "\nAll the drawers seem to be empty.\n"

        checkd_choices=("(1) Lift the floorboard?"
                "(2) search under the bed?"
                "(3) Go back & check another room?")


#       echo "(1)Go back and lift the floor board?"
#       echo "(2)Check under the bed?"
#       echo "(3)Check another room for clues?"

        for choice in ${checkd_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."
        read answer

        sleep 0.5

case $answer in
        1)
                echo -e "You lift the floor board and find a small wooden box."
                floorboard
                ;;

        2)
                echo -e "Checking under the bed."
                bed
                ;;

        3)
                echo -e "Checking another room for clues."
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac

}

sleep 0.5

bed() {
       echo -e "\nYou lift the mattress and check under the bed but nothing.\n"

        bed_choices=("(1) Search the dresser?"
                "(2) Go back & check another room?")

#        echo "(1)Check the dresser?"
#        echo "(2)Check another room for clues?"

        for choice in ${bed_choices[*]}
       do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e "As you walk over to the dresser to search it, you noticed a discolored and loose floor board. Upon closer inspection you notice that it's loose."
                dresser_1
                ;;

        2)
                echo -e "Checking under the bed."
                bed
                ;;
        3)
                echo -e "Checking another room for clues."
                another_room
                ;;

        *)
                echo -n "invalid"
               ;;

        esac
}

sleep 0.5

dresser_1() {

        dresser1_choices=("(1) Lift the floorboard?"
                "(2) Might be nothing, search the dresser instead?"
                "(3) Go back & check another room?")

#        echo -e "\n(1)Lift the floor board?"
#        echo "(2)Might be nothing, check the dresser instead?"
#        echo "(3)Check another room for clues?"

        for choice in ${dresser1_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."
        read answer

        sleep 0.5

case $answer in
        1)
                echo -e "You lift the floor board and find a small wooden box."
                floor_board
                ;;

        2)
                echo -e "Searching the dresser."
                check_dresser
                ;;

        3)
                echo -e "Checking another room for clues."
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac
}

sleep 0.5

floorboard() {
       dresser1_choices=("(1) Yes?"
                "(2) No, it might be haunted?"
                "(3) Its probably nothing, put it back and check another room?")

        echo -e "\nOpen the box?\n"

#        echo "(1)Yes?"
#        echo "(2)No, it might be haunted?"
#        echo "(3)It's probably nothing, just leave put it back and check another room?"
#        echo "(4)Leave the house, there's probably no clues leading to the treasure."

        for choice in ${floorboard_choices[*]}
        do
                echo "${choice}"
                sleep 0.5
        done
        sleep 0.5

        echo "Waiting for your move..."

        read answer

        sleep 0.5

case $answer in
        1)
                echo -e "\nYou open the box and find, a map that has the initals "AK" on it. It's a treasure map! Seems to be where C"
               treasure_map
                ;;

        2)
                echo -e "Ghosts aren't real right?"
                bed
                ;;

        3)
                echo -e "Checking another room for clues."
                another_room
                ;;

        *)
                echo -n "invalid"
                ;;

        esac
}

sleep 0.5

treasure_map() {

        echo -e "\nYou leave the house and make your way to the Church\n"

sleep 0.5

        echo -e "\n====Level 3====\n"

source level3.sh

}
main_menu
